require: rubocop-rspec

RSpec/NestedGroups:
  Max: 4

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/InheritException:
  EnforcedStyle: standard_error

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/BlockLength:
  ExcludedMethods:
    - class_scope
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
Style/RaiseArgs:
  EnforcedStyle: compact

Metrics/LineLength:
  Max: 100

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - _
    - id
